### PR TITLE
support phi 3

### PR DESCRIPTION
**Pull request by ZX-ModelCloud**

### CODE REVIEW

**Comment by Qubitium** [comment]
@davidgxue  We have validated this PR with modfications on real model quant with pre/post PPL. Ready for merge. Thank you for the Phi3 code!

**Comment by Qubitium** [comment]
Test Result:

Phi-3-medium-4k-instruct 
Native PPL: 4.189669132232666
Format gptq_v2, Quantized PPL: 4.834439754486084

**Comment by davidgxue** [comment]
Awesome work and thank you for adding me on here haha! AutoGPTQ library still seems glitchy? Both LLAMA 3 and Phi3 quants from AutoGPTQ has gibberish output issues when using with transformers... Hopefully this repo is better maintained!

**Comment by Qubitium** [comment]
@davidgxue Phi3 appears to contain fused modules and from our experience, any fused modules, will result in less than ideal calibration. That's why you see the Phi-3 post quant much higher (diff vs pre-quant) than other models. As such,  worse output is expected but I still do an issue with bad/gibberish.

If you can provide me with examples of gibberish (are these generated on native or gptq qunated) models? I would highly reocmmend you to re-quant them use GPTQModel as our internal code vs AutoGPTQ will in many cases by default generate higher quality quants due to the optimizations we have made. 

> Hopefully this repo is better maintained!

This is our pledge, mission statement, and core reason why I pushed our team to fork AutoGPTQ.

**Comment by davidgxue** [comment]
Oh yeah the fused modules part is definitely expected. 

What I meant is LLAMA 3 and Phi 3 (well i guess they are both llama family maybe) literally not working. I have had this issue open for a long time on AutoGPTQ repo, and im not the only one cuz I released a few GPTQ quants on huggingface and im being spammed in DM or huggingface issues about people experiencing the exact same thing.
https://github.com/AutoGPTQ/AutoGPTQ/issues/657

> This is our pledge, mission statement, and core reason why I pushed our team to fork AutoGPTQ.

Love it! Will follow you guys and see if there are stuff I can help out on!

**Pull request merged**
