### PR TITLE
Add minicpm support

### PR DESCRIPTION
**Pull request by Qubitium**
Test Passed. 

Native PPL: 8.9361
Quant: PPL: 10.1709 (Format: gptq)

### CODE REVIEW

**Comment by Qubitium** [comment]
@LDLINGLINGLING  We have added Minicpm and tested with minicpm2-dpo-bfloat16 model.

**Comment by LDLINGLINGLING** [comment]
If passed, can it be merged into the autogptq main code?

**Comment by Qubitium** [comment]
@LDLINGLINGLING  This repo was forked because AutoGPTQ maintainers have no time checking even simple bug-fix PRs. You can wait for them to check but I would not recommend it. At this project, we will validate and merge as soon as validations are passed.

**Comment by LDLINGLINGLING** [comment]
ok, thank you very much

**Pull request merged**
